name: CI
on: [push, workflow_dispatch]
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read Data
        id: readdata
        uses: natescherer/changelog-management-action@main
        with:
          path: test\CHANGELOG1.md
      - name: Release
        id: release
        uses: natescherer/changelog-management-action@main
        with:
          path: test\CHANGELOG2.md
          mode: release
          releaseversion: 2.0.0
      - name: Map Outputs to env vars
        run: |
          $ReadLastVersion = "${{ steps.readdata.outputs.lastversion }}"
          echo "READ_LASTVERSION=$ReadLastVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          $ReadReleaseNotes = "${{ steps.readdata.outputs.releasenotes }}"
          echo "READ_RELEASENOTES=$ReadReleaseNotes" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          $ReleaseLastVersion = "${{ steps.release.outputs.lastversion }}"
          echo "RELEASE_LASTVERSION=$ReleaseLastVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          $ReleaseReleaseNotes = "${{ steps.release.outputs.releasenotes }}"
          echo "RELEASE_RELEASENOTES=$ReleaseReleaseNotes" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Run Pester Tests
        id: pester
        uses: natescherer/pester-tests-report@feature/code-coverage
        with:
          report_name: TestResults_${{ runner.os }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: ${{ env.BARE_REPOSITORY }}_TestResults_${{ runner.os }}.md
          gist_badge_label: ${{ runner.os }}
          gist_token: ${{ secrets.PESTER_GIST_TOKEN }}
          tests_fail_step: true